[package]
name = "healthcheck-server"
version = "0.1.0"
edition = "2021"
description = "A healthcheck server"

[[bin]]
name = "HealthCheckServer"
path = "main.rs"

[dependencies]
actix-web = "4.0.0-beta.8"